In [1]:
import pandas as pd
df = pd.read_csv('purchase.csv')

In [2]:
df.head

<bound method NDFrame.head of     Customer id  Age  Gender     Item  Count Size  Review Discount  \
0             1   30    Male    Shirt      1    L     3.2       No
1             2   35    Male     Pant      1    M     4.4       No
2             3   16  Female   Shorts      3   XL     5.0      Yes
3             4   20    Male    Shirt      3  XXL     3.5      Yes
4             5   22  Female    Saree      2    M     4.6       No
5             6   35  Female    Saree      1    L     4.9       No
6             7   60    Male    Shirt      2    L     4.0       No
7             8   46    Male  Trousar      2    M     3.9       No
8             9   47  Female    Saree      1   XL     3.5       No
9            10   67    Male    Shirt      2    L     3.6       No
10           11   53  Female   shorts      1  XXL     4.0       No
11           12   15    Male    Shirt      3   XL     4.2      Yes
12           13   36  Female    Saree      4    M     4.1      Yes
13           14   29    Male     pant      5    M     2.0      Yes
14           15   40  Female   Blowse      3  XXL     3.8      Yes
15           16   32    Male  Trousar      2    M     3.5       No
16           17   44    Male    Shirt      1    M     4.8       No
17           18   53    Male    Saree      3    M     4.5      Yes
18           19   17  Female   Shorts      4    L     4.0      Yes
19           19   16  Female    Saree      2    L     3.0       No
20           21   19    Male    Shirt      3   XL     3.9      Yes
21           22   40  Female   Shorts      1  XXL     5.0       No
22           23   33    Male     pant      1    M     3.3       No
23           24   37  Female    Shirt      1    L     4.0       No
24           25   50    Male    Shirt      3    M     4.2      Yes
25           26   27  Female    Saree      2  XXL     4.0       No
26           27   26  Female    Saree      5    M     5.0      Yes
27           28   25    Male    Shirt      4    M     4.4      Yes
28           29   19    Male   Blowse      3    M     4.1      Yes
29           30   20  Female    Shirt      2    L     3.0       No
30           31   40  Female     Pant      1   XL     3.7       No
31           32   35  Female     Pant      2  XXL     4.0       No
32           33   39  Female  Trousar      3    L     5.0      Yes
33           34   45    Male    Shirt      2    M     4.9       No
34           35   23    Male     Pant      1    L     4.5       No
35           36   49  Female     Pant      2    L     3.0       No
36           37   55  Female     Pant      1    M     3.6       No
37           38   59    Male    Saree      2   XL     3.1       No
38           39   28    Male    Saree      3  XXL     2.7      Yes
39           40   34  Female    Saree      4   XL     4.7      Yes
40           41   29    Male     Pant      2    M     5.0       No
41           42   48    Male  Trousar      1    M     4.8       No
42           43   27    Male  Trousar      5    M     4.6      Yes
43           44   19    Male  Trousar      2    L     3.6       No
44           45   17  Female    Shirt      1    L     3.9       No
45           46   20    Male    Shirt      1   XL     3.8       No
46           47   47    Male    Shirt      2    L     3.5       No
47           48   33  Female   Blowse      3    M     4.8      Yes
48           49   20  Female    Saree      2    S     5.0       No

          Payment Previous purchase
0            Cash                 3
1     Credit card                 2
2   Bank transfer                 4
3            Cash                 2
4      Debit card                 5
5     Credit card                 6
6      Debit card                 3
7   Bank transfer                 4
8            Cash                 5
9   Bank transfer                 2
10     Debit card                 7
11     Debit card                 6
12     Debit card                 4
13    Credit card                 3
14    Credit card                 1
15           Cash                 2
16           Cash                 7
17           Cash                 8
18           Cash                No
19           Cash                 2
20           Cash                No
21           Cash                 3
22           Cash                 3
23           Cash                 1
24    Credit card                 9
25     Debit card                 7
26     Debit card                 4
27     Debit card                 5
28           Cash                 6
29           Cash                No
30    Credit card                No
31  Bank transfer                No
32  Bank transfer                 8
33  Bank transfer                 5
34           Cash                 4
35     Debit card                 3
36    Credit card                No
37           Cash                No
38           Cash                No
39           Cash                No
40           Cash                 8
41           Cash                 3
42           Cash                 6
43     Debit card                 8
44           Cash                No
45  Bank transfer                No
46           Cash                No
47           Cash                No
48           Cash                No  >

In [4]:
df.isnull().sum()

Customer id          0
Age                  0
Gender               0
Item                 0
Count                0
Size                 0
Review               0
Discount             0
Payment              0
Previous purchase    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace (' ','_' )
df.to_sql("mytable", engine, if_exists="replace", index=False)

49

In [4]:
df.columns

Index(['customer_id', 'age', 'gender', 'item', 'count', 'size', 'review',
       'discount', 'payment', 'previous_purchase'],
      dtype='object')

In [6]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
pip install mysql-connector-python pandas sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (9.5.0)
Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.3.2)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (1.1.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.14.1)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#CODE FOR CONNECTION

import mysql.connector
import pandas as pd
from sqlalchemy import create_engine

# Connect MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="2007",
    database="pda",
    port=3306
)

print("Connected Successfully")

# Create SQLAlchemy engine
engine = create_engine(
    "mysql+pymysql://root:2007@localhost:3306/pda"
)

# Store into MySQL
table_name = "mytable"

df.to_sql(table_name, engine, if_exists='replace', index=False)

# Read from MySQL
pd.read_sql("SELECT * FROM mytable LIMIT 5;", engine)

Connected Successfully

,Customer id,Age,Gender,Item,Count,Size,Review,Discount,Payment,Previous purchase
0,1,30,Male,Shirt,1,L,3.2,No,Cash,3
1,2,35,Male,Pant,1,M,4.4,No,Credit card,2
2,3,16,Female,Shorts,3,XL,5.0,Yes,Bank transfer,4
3,4,20,Male,Shirt,3,XXL,3.5,Yes,Cash,2
4,5,22,Female,Saree,2,M,4.6,No,Debit card,5

In [7]:
# CODE FOR IMPORT CSV

import pandas as pd
from sqlalchemy import create_engine


# MySQL Connection
engine = create_engine(
    "mysql+pymysql://root:2007@localhost:3306/pda"
)

# Upload CSV to MySQL
df.to_sql(
    name="purchase",
    con=engine,
    if_exists="replace",
    index=False
)

# Check Data
result = pd.read_sql(
    "SELECT * FROM purchase LIMIT 5",
    engine
)

print(result)

   Customer id  Age  Gender    Item  Count Size  Review Discount  \
0            1   30    Male   Shirt      1    L     3.2       No
1            2   35    Male    Pant      1    M     4.4       No
2            3   16  Female  Shorts      3   XL     5.0      Yes
3            4   20    Male   Shirt      3  XXL     3.5      Yes
4            5   22  Female   Saree      2    M     4.6       No

         Payment Previous purchase age_group
0           Cash                 3     adult
1    Credit card                 2     adult
2  Bank transfer                 4     youth
3           Cash                 2     youth
4     Debit card                 5     youth

In [4]:
#create a column
labels=['youth','adult','aged']
df['age_group'] = pd.qcut(df['Age'], q=3, labels = labels)
df[['Age','age_group']].head()
df.to_sql("mytable", engine, if_exists="replace", index=False)

49

In [5]:
#SENDING NEW MESSEGES TO SQL
df.to_sql(
    name='mytable',  
    con=engine,
    if_exists='replace', 
    index=False
)

49

In [8]:
male_items = ['Shirt', 'Pant', 'Trouser']

df['maleitems'] = df['Item'].apply(
    lambda x: x if x in male_items else None
)

df[['Item', 'maleitems']].head()

     Item maleitems
0   Shirt     Shirt
1    Pant      Pant
2  Shorts      None
3   Shirt     Shirt
4   Saree      None

In [3]:
df.describe()

       Customer id        Age      Count     Review
count    49.000000  49.000000  49.000000  49.000000
mean     24.979592  34.204082   2.265306   4.032653
std      14.296692  13.495338   1.168609   0.706042
min       1.000000  15.000000   1.000000   2.000000
25%      13.000000  22.000000   1.000000   3.600000
50%      25.000000  33.000000   2.000000   4.000000
75%      37.000000  45.000000   3.000000   4.600000
max      49.000000  67.000000   5.000000   5.000000

In [6]:
df.shape

(49, 11)